services:
  wfagent:
    image: ghcr.io/shaunbrady/caroniagent-wf_agent:v0.0.2
    environment:
      DATABASE_URL: postgres://myuser:mypassword@agentdb:5432/mydb
      AMQP_URL: amqp://user:pass@rabbitmq:5672/
    depends_on:
      - agentdb
      - agentweb # Hack to avoid DB not being fully available
    networks:
      - default
      - caroni_shared_net

  agentweb:
    image: ghcr.io/shaunbrady/caroniagent-django:v0.0.2
    ports:
      - "8001:8000"
    environment:
      DATABASE_URL: postgres://myuser:mypassword@agentdb:5432/mydb
    depends_on:
      - agentdb

  agentdb:
    image: postgres:16
    environment:
      POSTGRES_DB: mydb
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    volumes:
      - agentpgdata:/var/lib/postgresql/data

volumes:
  agentpgdata:

networks:
  caroni_shared_net:
    external: true
